[project]
name = "odoo-addons-oca-wms"
version = "18.0.20241231.0"
dependencies = [
    "odoo-addon-delivery_carrier_warehouse==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
